### Question_1:
    Write a program to create a 5 dimentional array with all zeros and ones.

In [1]:
import numpy as np

In [10]:
np.zeros((1,1,1,5,4))

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [11]:
np.ones((1,1,1,5,4))

array([[[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]]])

### Question_2:
    Write a program to create an array of 10 zeros, 10 ones, 10 fives in row 1,2 and 3 which create a new array of shape       (3,10)

In [75]:
a = np.zeros(10,dtype = int),np.ones(10,dtype = int),np.full(10,5)
print("shape is : ", np.shape(a))
a

shape is :  (3, 10)


(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]))

In [77]:
zeros = np.zeros(10,dtype = int)
ones = np.ones(10,dtype = int)
fives = np.full(10,5)
np.vstack((zeros,ones,fives))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

### Question_3:
    Write a program to create a 3x4 matrix filled with values from 10 to 21

In [22]:
np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

### Question_4:
    Write a program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9

In [32]:
a = np.diag(np.arange(0,10))
print(np.shape(a))
a

(10, 10)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

### Question_5:
       Write a program to create 4x4 array. Create an array from below array br swapping first and last, second and third         columns.

In [136]:
a = np.array([np.arange(1,17)]).reshape(4,4)
print(a)
a[:,(3,2,1,0)]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

### Question_6:
    Write a program to reverse an array (the first element becomes the last).
    Given array:
        [12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27]

In [141]:
a = np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27])
a[::-1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

### Question_7:
    Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of           shape 10,10. Elements range from 1 to 100

In [153]:
a = np.arange(1,101).reshape(10,10)
a[(a>30) & (a<80) & (a % 5 == 0)]

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

### Question_8:
    Write a program to create a 2D array with 1 on the border and 0 inside.

In [20]:
a = np.ones((10,10), dtype = int)
a[1:9,1:9] = 0
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### Question_9:
    Write a program to create a chekerboard pattern. Don't use default array function.

In [72]:
a = np.ones((20,10),dtype =int)
for i in range(len(a)):
    if i % 2 == 0:
        (a[i])[::2] = 0
    else:
        (a[i])[1::2] = 0
a

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

### Question_10:
    Write a program to find common values between two arrays

In [154]:
a = np.array([10,20,30,40,50])
b = np.array([10,30,50,70,90])
np.intersect1d(a,b)

array([10, 30, 50])

### Question_11:
    Write a program to create an 2d array then reshape into 1d array.

In [5]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [6]:
# method - 1
a.reshape(25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [7]:
# method - 2
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [8]:
# method - 3
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

### Question_12:
    Write a user defined function for creating a 1d or 2d without using array functions

In [4]:
def array():
    array = int(input("Enter 1 for 1-D array \nEnter 2 for 2-D array :  "))
    if array == 2:
        function = (input("Enter '1' for ones(),\nEnter '0' for zeros,\nEnter 'any number' for full() ::   "))
        function = " "+function
        a = int(input("Enter number of rows :  "))
        b = int(input("enter number of columns :  "))
        if b == 0 :
            print(a*function)
        else:
            print("array")
            for i in range(a):
                print(b*function)               
                    
    elif array == 1:
        function = (input("Enter '1' for ones(),\nEnter '0' for zeros,\nEnter 'any number' for full() ::   "))
        function = " "+function
        a = int(input("Enter the number of elements :  "))
        print("array")
        return(a * function)
           
    else:
        print("Please enter a valid input...")

In [4]:
array()

Enter 1 for 1-D array 
Enter 2 for 2-D array :  2
Enter '1' for ones(),
Enter '0' for zeros,
Enter 'any number' for full() ::   10
Enter number of rows :  5
enter number of columns :  5
array
 10 10 10 10 10
 10 10 10 10 10
 10 10 10 10 10
 10 10 10 10 10
 10 10 10 10 10


In [5]:
array()

Enter 1 for 1-D array 
Enter 2 for 2-D array :  1
Enter '1' for ones(),
Enter '0' for zeros,
Enter 'any number' for full() ::   0
Enter the number of elements :  10
array


' 0 0 0 0 0 0 0 0 0 0'