In [1]:
import numpy as np

# tipsf

In [153]:
a = np.genfromtxt(r"C:\Users\91991\OneDrive\Desktop\python 243\Python 243 tasks\Numpy assignments\tipsf.csv",delimiter = ",",skip_header = 1)

In [86]:
a

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

### Question_1:
    What is the total bill value ?

In [87]:
print(f"The total bill value is :  {sum(a[::,1])}")

The total bill value is :  4827.770000000001


In [88]:
print(f"The total bill value is :  {np.sum(a[::,1])}")

The total bill value is :  4827.77


### Question_2:
    What is the total tip value ?

In [89]:
print(f"The total tip value is :  {sum(a[::,2])}")

The total tip value is :  731.58


In [90]:
print(f"The total tip value is :  {np.sum(a[::,2])}")

The total tip value is :  731.5799999999999


### Qeustion_3:
    Count how many sundays, saturdays, thursdays and fridays are there ?

In [135]:
np.unique(a[:,5],return_counts = True) 

(array([0., 1., 2., 3.]), array([87, 76, 62, 19], dtype=int64))

In [144]:
a1 = np.unique(a[:,5],return_counts = True)
print(f"""The number of Sundays({a1[0][0]}) are {a1[1][0]} 
The number of Saturdays({a1[0][1]}) are {a1[1][1]} 
The number of Thursdays({a1[0][2]}) are {a1[1][2]} 
The number of Fridays({a1[0][3]}) are {a1[1][3]}""")

The number of Sundays(0.0) are 87 
The number of Saturdays(1.0) are 76 
The number of Thursdays(2.0) are 62 
The number of Fridays(3.0) are 19


### Question_4:
    How many smokers are there ?

In [10]:
print(f"The total number of smokers are :  {np.sum(a[:,4])} ")

The total number of smokers are :  93.0 


### Question_5:
    What is the average tip given by female and male.?

In [160]:
np.mean(a[a[:,3] == 0][:,2])

2.8334482758620685

In [163]:
a2 = a[a[:,3] == 0][:,2]
sum(a2)/len(a2)

2.833448275862069

### Question_6:
    How much amount have been spent by female & male?

In [176]:
print(f"The total amount spent by females are :  {sum(a[a[:,3] == 0][:,1])}")
print(f"The total amount spent by males are :  {sum(a[a[:,3] == 1][:,1])}")

The total amount spent by females are :  1570.9499999999998
The total amount spent by males are :  3256.8200000000024


### Question_7:
    What is the min & max tip given ?

In [20]:
print(f"The max tip given is :  {max(a[:,2])}")
print(f"The min tip given is :  {min(a[:,2])}")

The max tip given is :  10.0
The min tip given is :  1.0


### Question_8:
    How many male and females are going for dinner and lunch ?

In [216]:
print(f"The number of 'Females' going for dinner are :  {np.unique(a[a[:,3] ==0,6],return_counts = True)[1][0]}")
print(f"The number of 'Females' going for lunch are :  {np.unique(a[a[:,3] ==0,6],return_counts = True)[1][1]}")
print(f"The number of 'Males' going for dinner are :  {np.unique(a[a[:,3] ==1,6],return_counts = True)[1][0]}")
print(f"The number of 'Males' going for lunch are :  {np.unique(a[a[:,3] ==1,6],return_counts = True)[1][1]}")

The number of 'Females' going for dinner are :  52
The number of 'Females' going for lunch are :  35
The number of 'Males' going for dinner are :  124
The number of 'Males' going for lunch are :  33


### Question_9:
    Find out the Avg size

In [241]:
(sum(a[:,7]))/(len(a[:,7]))

2.569672131147541

In [28]:
np.mean(a[:,7])

2.569672131147541

### Questin_10:
    How many female smokers are there and how many male smokers are there ?

In [239]:
print(f"The total number of smokers are :  {sum(a[:,4])}")
print(f"The number of 'Female' smokers are :  {sum(a[a[:,3] ==0,4])}")
print(f"The number of 'Male' smokers are :  {sum(a[a[:,3]==1,4])}")

The total number of smokers are :  93.0
The number of 'Female' smokers are :  33.0
The number of 'Male' smokers are :  60.0


# train_extended

In [243]:
b = np.genfromtxt(r"C:\Users\91991\OneDrive\Desktop\python 243\Python 243 tasks\Numpy assignments\train_extended.csv",delimiter = ",",skip_header = 1)

In [244]:
print("0 - length ,1 - Diameter  , 2 - Height  , 3 - Weight   , 4 - Shucked weight  , 5 - Viscera weight , 6 - Shell weight  , 7 - Age")
b

0 - length ,1 - Diameter  , 2 - Height  , 3 - Weight   , 4 - Shucked weight  , 5 - Viscera weight , 6 - Shell weight  , 7 - Age


array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

### Question_1:
    What is the max and min lenght ?

In [4]:
print(f"The max lenght is :  {max(b[:,0])}")
print(f"The min lenght is :  {min(b[:,0])}")

The max lenght is :  7.58349125
The min lenght is :  0.0


### Question_2:
    Find out the difference between max and min length ?

In [5]:
max(b[:,0]) - min(b[:,0])

7.58349125

### Question_3:
    Find column wise average ?

In [109]:
np.mean(b,axis = 0)

array([ 1.31244808,  1.02032036,  0.34602787, 23.12343631,  9.98937025,
        4.99318096,  6.63422915,  9.950615  ])

### Question_4:
    Find out all the Age whose height is >  0.4 ?

In [7]:
b[b[:,2]>0.4,7]

array([11., 14., 13., ..., 11., 11., 11.])

### Question_5:
    What is the average height and weight of the persons whose age is 10 ?

In [8]:
print(f"The average height of the persons whose age is 10 is :  {np.mean(b[b[:,7] == 10,2])}")
print(f"The average weight of the persons whose age is 10 is :  {np.mean(b[b[:,7] == 10,3])}")

The average height of the persons whose age is 10 is :  0.3833672856539947
The average weight of the persons whose age is 10 is :  28.243308450511314


### Question_6:
    What is the total shell weight ?

In [242]:
print(f"The total Shell Weight is :  {sum(b[:,6])}")

The total Shell Weight is :  1326845.8295212665


### Question_7:
    How many Persons belongs to each and every unique age ?

In [10]:
np.unique((b[:,7]),return_counts = True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))

In [245]:
x = np.unique((b[:,7]),return_counts = True)[0]
y = np.unique((b[:,7]),return_counts = True)[1]


for i in range(min(len(x), len(y))):
    print(f"Number of persons of age {x[i]} are {y[i]}")



Number of persons of age 1.0 are 46
Number of persons of age 2.0 are 42
Number of persons of age 3.0 are 625
Number of persons of age 4.0 are 2787
Number of persons of age 5.0 are 5475
Number of persons of age 6.0 are 12450
Number of persons of age 7.0 are 18276
Number of persons of age 8.0 are 26818
Number of persons of age 9.0 are 32906
Number of persons of age 10.0 are 30803
Number of persons of age 11.0 are 23457
Number of persons of age 12.0 are 12717
Number of persons of age 13.0 are 10037
Number of persons of age 14.0 are 6352
Number of persons of age 15.0 are 4831
Number of persons of age 16.0 are 3191
Number of persons of age 17.0 are 2705
Number of persons of age 18.0 are 1953
Number of persons of age 19.0 are 1591
Number of persons of age 20.0 are 1206
Number of persons of age 21.0 are 721
Number of persons of age 22.0 are 296
Number of persons of age 23.0 are 352
Number of persons of age 24.0 are 110
Number of persons of age 25.0 are 51
Number of persons of age 26.0 are 46


### Question_8:
    What is the difference between shucked weight and viscera weight ?

In [12]:
b[:,4] - b[:,5]

array([5.9817445, 3.855532 , 4.1106775, ..., 2.9199985, 5.329706 ,
       9.8372765])

### Question_9:
    What is the average height of the persons whose age is between 14 & 19. ?

In [49]:
np.mean((b[:,7]>=14) & (b[:,7]<=19))

0.103115

### Question_10:
    What is the average weight if we include Shucked weight, Viscera weight and Shell weight ? 

In [83]:
np.mean(b[:,4] + b[:,5] + b[:,6])

21.616780352404746